import Head from 'next/head'
import { Portfolio } from 'views/Portfolio'

export default function Index() {
  return (
    <>
      <Head>
        <title>Alfredo Tito - Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Portfolio />
    </>
  )
}
