import Head from 'next/head'
import { About } from 'views/About'

export default function Index() {
  return (
    <>
      <Head>
        <title>Alfredo Tito - Sobre</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <About />
    </>
  )
}
