import Head from 'next/head'
import { Website } from 'views/Website'

export default function Index() {
  return (
    <>
      <Head>
        <title>Por que ter um site?</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Website />
    </>
  )
}
